const express = require("express");
const multer = require("multer");
const fs = require("fs");
const pdfParse = require("pdf-parse");
const OpenAI = require("openai");
const ExcelJS = require("exceljs");

// Load environment variables
require("dotenv").config();

if (!process.env.OPENAI_API_KEY) {
  console.error("ERROR: Missing OPENAI_API_KEY in .env file.");
  process.exit(1);
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const app = express();
const upload = multer({ dest: "uploads/" });

app.set("view engine", "ejs");
app.use(express.static("public"));

// Full prompt with all codes, descriptions, and examples
const codebook = `
You are a Human-Computer Interaction researcher and are coding the articles selected in the Systematic Literature Review.
Below are the codes that should guide your classification. For each code, find relevant excerpts in the article, identify them, and classify them.

Code: A. Overview
Description: Summary of what the article proposes.
Example excerpts:
- "This paper aims to explore the level of citizen participation in the Songdo smart city project [...] using new IT technology."
- "This study aims to address the research gap by proposing a framework for citizen-centric smart city design."
- "The research proposes that a design thinking framework can improve collaboration in urban projects."
- "In order to help smart cities provide responsive services, this paper develops a citizen-centered tool."
- "This paper creates a methodological approach to assess citizen readiness for smart city initiatives."

Code: B. Context of use
Description: Components of the context of use of the environment considered in the design process (e.g., technologies, sensors, mobile devices).
Example excerpts:
- "The urbanization of cities and the need to provide quality services to citizens have become major challenges for governments."
- "ClouT focuses on leveraging Cloud computing to bridge IoT and people through services."
- "As such, the U-city project mainly considered urban infrastructure using information platforms."
- "NOMAD is a platform for policymakers to monitor and analyze citizens’ discussions on social media."
- "The framework promotes the development of a city commons using accessible resources like data and technology."

Code: C1. Technologies
Description: List of specific technologies mentioned in smart city design projects.
Example excerpts:
- "The Frogbox was designed to collect data every five minutes using a Python script and store it in MySQL."
- "IoT and legacy devices were combined to create seamless interaction."
- "Sentiment analysis was used to interpret user opinions on urban policies."
- "The Monogatari framework was used to create interactive visual novels."
- "The U-city strategy combines IT technology to deliver various city services."

Code: C2. Functions and applications
Description: Description of the functions and applications of these technologies in urban contexts.
Example excerpts:
- "The system monitors air quality and alerts citizens via mobile apps."
- "IoT devices collect real-time data on traffic flow to optimize city planning."
- "Smart meters track energy consumption and provide feedback to users."
- "The system uses sensors to detect and report waste overflow in urban bins."
- "A mobile app visualizes pedestrian movement to improve accessibility."

Code: C3. Use cases or real implementations
Description: Examples of use cases or real implementations of these technologies in design projects.
Example excerpts:
- "DColbici3 models scenarios as visual novels that participants can play to discover and evaluate situations."
- "A mobility scenario in Madrid was modeled to identify obstacles for people with reduced mobility."
- "Field trials were conducted in multiple cities to test a smart city platform."
- "A pilot project monitored water quality using IoT sensors in a coastal city."
- "The ClouT platform enables IoT and social media integration for decision-making."

Code: C4. How manage data
Description: Methods for the collection, integration, and analysis of data generated by sensors, actuators, and mobile devices.
Example excerpts:
- "Data collected from sensors is processed using real-time analytics to detect anomalies."
- "The platform integrates data from IoT devices and social media using cloud computing."
- "Raw data is pre-processed to remove noise before analysis."
- "Geospatial data is analyzed to identify traffic hotspots."
- "The system uses machine learning to classify patterns in urban data."

Code: C5. Data sources
Description: Data sources (e.g., sensors, mobile devices).
Example excerpts:
- "IoT sensors installed in public areas collect real-time air quality data."
- "Mobile devices were used to gather citizen feedback on public services."
- "Social media platforms like Twitter and Facebook were analyzed for public sentiment."
- "Cameras at traffic intersections monitor vehicle flow and send data to the cloud."
- "Smart meters provide real-time data on household energy usage."

Code: D1. How to deal with heterogeneity
Description: Approaches for dealing with the heterogeneity of the urban and usage context.
Example excerpts:
- "The platform gathers feedback from citizens with diverse needs to propose inclusive solutions."
- "The system integrates IoT devices and traditional communication platforms for seamless interaction."
- "Simulation tools were designed to accommodate various disabilities in urban scenarios."
- "Legal restrictions limited the scope of paid services, requiring alternative strategies."
- "Social media platforms lack compatibility with government participation tools."

Code: D2. Incorporate technologies into design process
Description: Strategies used to incorporate technologies into the design process.
Example excerpts:
- "Stakeholders identified necessary skills and designed training to help communities use technologies."
- "A three-stage process was developed: stakeholder interaction, development, and field trials."
- "The U-city strategy focused on combining IT technologies to deliver city services."
- "Government recognized citizen contributions and updated system rules to ensure inclusivity."
- "IoT devices were integrated with participatory platforms for citizen engagement."

Code: D3. Stakeholder engagement strategies
Description: Stakeholder engagement strategies.
Example excerpts:
- "Meeting participants included citizens, municipalities, and companies who provided feedback."
- "Group discussions were held to collect ideas and perspectives on city projects."
- "Cultural differences between participants shaped the feedback collected during trials."
- "Workshops were organized to involve local communities in co-design efforts."
- "Participants provided diverse feedback based on their daily life experiences."

Code: D4. Technical issues addressed
Description: Technical issues addressed/encountered in the design process.
Example excerpts:
- "Challenges included authentication, data encryption, and resource allocation."
- "Initial stages of the project faced issues with data collection and public communication infrastructure."
- "Data diversity across social media platforms complicated data processing."
- "Interoperability issues arose between legacy systems and IoT devices."
- "The second problem is that the project focused only on surveillance services."

Code: D5. How technical issues are addressed
Description: How technical issues are addressed in the design process.
Example excerpts:
- "Challenges are addressed in the architecture through modular designs."
- "Social media platforms were integrated with IoT systems to improve data quality."
- "Citizen feedback was used to refine IoT system functionalities."
- "Machine learning algorithms were deployed to identify patterns and resolve inconsistencies in large datasets."
- "The system adopted adaptive communication protocols to handle varying network conditions."

Code: D6. Strategies or solutions to address the technical issues
Description: Strategies or solutions proposed to address these issues.
Example excerpts:
- "The Reference Architecture uses cloud service models to integrate IoT and Cloud Computing for scalable infrastructures."
- "An e-voting system was proposed to ensure democratic participation and reduce decision-making biases."
- "Social media and communication channels were combined to enhance citizen engagement."
- "Machine learning was applied to identify and correct data inconsistencies."
- "The modular design of the system allowed for incremental improvements based on user feedback."

Code: D7. Challenges
Description: Discussion on specific challenges related to implementation, interoperability, security, privacy, sustainability, among others.
Example excerpts:
- "Challenges included data encryption, interoperability, and scalability for global platforms."
- "Human aspects were often overlooked, leading to criticism in the design of smart cities."
- "Participation inequality and the digital divide excluded some citizens from contributing."
- "Technical constraints limited the integration of legacy systems with modern IoT devices."
- "Privacy concerns were raised due to the extensive data collection from urban environments."

Code: E1. Human aspects
Description: Human aspects addressed in the design process (e.g., communities, user needs and/or disabilities).
Example excerpts:
- "The design focused on inclusivity by addressing the needs of people with disabilities."
- "Special groups, such as minors and those affected by the digital divide, were included in participatory processes."
- "Citizens' satisfaction and loyalty were prioritized to ensure sustainable growth."
- "A case study modeled daily mobility challenges for people with reduced mobility."
- "Interactive tools were developed to make urban planning more accessible to citizens."

Code: E2. Participatory approach
Description: Name of the participatory approach.
Example excerpts:
- "This phase draws from User-Centered Design and Participatory Design frameworks."
- "The Citizen Participation Evaluation Framework categorizes citizens as co-creators, participants, or ICT users."
- "Surveys were conducted with citizens and stakeholders to collect diverse perspectives."
- "A synergy model allowed citizens to contribute and shape policy agendas."
- "Workshops enabled collaborative discussions between citizens and policymakers."

Code: E3. Codesign tools
Description: Methods/techniques/tools of co-design used in the design process.
Example excerpts:
- "Visual novels were used to simulate real-life scenarios and gather feedback."
- "Surveys were distributed to stakeholders to evaluate concepts."
- "Living labs and online platforms collected citizens' opinions on urban projects."
- "Interactive workshops were conducted to assess the viability of urban solutions."
- "Fieldnotes and interviews were used to evaluate community engagement."

Code: E4. Stakeholders
Description: Stakeholders involved in the design process.
Example excerpts:
- "Technology volunteers, city council members, and school children were involved in the design."
- "Municipalities, citizens, and application developers collaborated on the project."
- "Government and citizens worked together to ensure inclusivity."
- "Non-profits and local businesses contributed to urban challenge solutions."
- "Technical experts and environmental activists participated in the planning."

Action: Read the attached article and extract the excerpts that correspond to each code, using the descriptions and examples above as a guide. For each excerpt found, indicate the assigned code and provide the exact text from the article.
Guidelines:
* Be as precise as possible in your responses, without being creative.
* Respond with raw text excerpts from the article.
* Consider all sections in the extraction except the related works section (Literature Review, Theoretical Background, Related Work, State of the Art, Background, Review of the Literature, Research Background, Previous Studies, Existing Literature, Knowledge Base, Foundation of the Study, Research Context, Analysis of Related Research).
* Do not include code snippets that do not match any of the codes.
`;


// Function to process PDF and extract text
async function extractTextFromPdf(pdfPath) {
    const dataBuffer = fs.readFileSync(pdfPath);
    const pdfData = await pdfParse(dataBuffer);
    return pdfData.text;
}

// Function to process text with GPT API
async function processWithGPT(text, paperName) {
    const prompt = `${codebook}\n\nThe text is:\n${text}\n\nGuidelines: Use the examples as a guide to identify similar patterns in the text. Extract text strictly from the provided source. Do not create, infer, or modify text beyond what is explicitly stated.`;
    try {
        const response = await openai.chat.completions.create({
            model: "gpt-4o",
            temperature: 0.2,
            messages: [{
                    role: "system",
                    content: "You are a precise and detail-oriented assistant. Use the provided examples as a guide, but only extract text explicitly stated in the provided content. Do not generate or imagine text beyond the source material.",
                },
                {
                    role: "user",
                    content: prompt
                },
            ],
        });

        if (
            !response ||
            !response.choices ||
            !response.choices[0] ||
            !response.choices[0].message
        ) {
            console.error("Invalid response from OpenAI API.");
            return [];
        }

        // Parse GPT response into results
        const results = response.choices[0].message.content.split("\n").map((line) => {
            const [code, ...extractionParts] = line.split(":");
            return {
                paperName,
                code: code.trim(),
                excerpt: extractionParts.join(":").trim(),
            };
        });

        return results;
    } catch (error) {
        console.error("Error with OpenAI API:", error.response ?.data || error.message);
        return [];
    }
}

// Function to generate Excel file
async function generateExcel(results) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Results");

    // Add header row
    worksheet.columns = [{
            header: "Paper Name",
            key: "paperName",
            width: 30
        },
        {
            header: "Excerpt",
            key: "excerpt",
            width: 50
        },
        {
            header: "Code",
            key: "code",
            width: 15
        },
    ];

    // Add data rows
    let firstRow = true; // To handle the first occurrence of Paper Name
    let lastCode = "";
    results.forEach((result) => {


        if (result.excerpt != "") {
            lastCode = result.excerpt;
        }

        if (result.code != "**Code" && result.code != "") {
            worksheet.addRow({
                paperName: firstRow ? result.paperName : "",
                excerpt: result.code,
                code: lastCode,
            });
            //firstRow = false; // Ensure subsequent rows for the same paper omit the name
        }

    });

    const filePath = `results-${Date.now()}.xlsx`;
    await workbook.xlsx.writeFile(filePath);
    return filePath;
}

// Route to render the upload page
app.get("/", (req, res) => {
    res.render("index");
});

// Route to handle file upload and processing
app.post("/upload", upload.single("pdf"), async (req, res) => {
    if (!req.file) {
        return res.status(400).send("No file uploaded.");
    }

    const pdfPath = req.file.path;
    const paperName = req.file.originalname;

    try {
        // Extract text from PDF
        const pdfText = await extractTextFromPdf(pdfPath);

        // Process text with GPT
        const results = await processWithGPT(pdfText, paperName);

        // Generate Excel file
        const filePath = await generateExcel(results);

        // Send the file for download
        res.download(filePath, (err) => {
            if (err) {
                console.error("Error sending file:", err);
                res.status(500).send("Error generating or sending the file.");
            }

            // Clean up the generated file
            fs.unlinkSync(filePath);
        });
    } catch (error) {
        console.error("Error processing file:", error.message);
        res.status(500).send("An error occurred while processing the file.");
    } finally {
        // Clean up uploaded file
        fs.unlinkSync(pdfPath);
    }
});

// Start the server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});